### ISSUE TITLE
Wrong project

### ISSUE THREAD

**Issue by Philipdl** [42ndCo/Harvest-Time-Tracking#5]
Hi
I experience a problem that your plugin just propose the first project and doest take into account if the issue is related to another project. This happens often when i move around between projects.

I am using Chrome on mac.

**Comment by MartinPeverelli** [comment]
Hi @Philipdl 
We deployed several changes yesterday, which might have affected the _remembered_ projects from the previous version.
The current functionality tries to match the JIRA Project's code and name with the Harvest Project's code and name (respectively), and it autoselects the closest match.
However, once a user manually selects a project (and task) from the dropdown for a given JIRA Issue, that project (and task) is always remembered when loading JIRA Issues from the same JIRA Project.

I'd recommend to clear your browser's cache in order to ensure you are running our latest version, even though the update should be automatic.

Here is a screenshot of the new dropdown:
![screenshot 2018-02-08 14 17 35](https://user-images.githubusercontent.com/2745975/35987596-e183c450-0cda-11e8-93e4-9c29d5b66101.png)

Please let me know if this resolves your issue.

In case it doesn't, could you provide us with some more information regarding the JIRA & Harvest project codes and names? We fear this might be an issue with special characters due to internationalization support.

Thanks!

**Comment by Philipdl** [comment]
Hi 
We still experience problems even though we clear cache.
The dropdown is also a little buggy when you scroll.

Best Regards

Philip




-- 
Med venlig hilsen/Kind regards

Philip Danhøj Larsen
Project Manager

appstract
Rued Langgaards Vej 8
2300 København S


Mobil: +45 3175 5794
Mail: pdl@appstract.dk

**Comment by MartinPeverelli** [comment]
Hi,
Regarding the _bugginess_ of the dropdown, it is possible to see a little _stutter_ when scrolling, since the dropdown doesn't want to show a _group label_ (client) without a valid option for that group (project). So, it jumps to the first option available.
If this is the bugginess you see when you scroll, then it is expected for now. We'll try to smooth that out as we get to polish the UI.

On the autoselect side of your issue, I'm currently testing with JIRA and Harvest with dozens of projects and issues.
The plugin works as expected, which means that the auto-selection sometimes works, sometimes it doesn't. But once I manually set the project/task (harvest) in a given issue associated with X project in JIRA, it always loads the same project/task (harvest) for any issue in that X project.

The part that "sometimes works, sometimes doesn't" is the part when the plugin tries to match the current JIRA project with one of the projects in the harvest dropdown. This is done by comparing the JIRA Project Key with all the Harvest Project Codes, and the JIRA Project Name with all the Harvest Project Names. We sort them by their levenshtein distance, and pick the first one. 
So this is far from perfect, and it can produce odd results. But it is placed only as a convinience for first loads.
Once you as a user, manually chose a project/task, it will always load that project/task for the same JIRA project, regardless of the issue. 

If the plugin is not remembering your previous selections when moving from project to project in jira, then we'll need to get some more information from you to reproduce.
If the plugin is not autoselecting the "correct" choice of project in the dropdown for a given jira issue/project, when you haven't previously made any selections, but you think it should, then we'll need to ask you for some testing data in order to reproduce on our side.

If you are not comfortable sharing any of this on github issues, please email us at info@42nd.co

Thanks!

**Comment by MartinPeverelli** [comment]
@Philipdl we are going to deploy a new version of the plugin, that should fix the problem you reported.
What you experience on your end, was happening because the JIRA project fetching (API request) and the Harvest project/client fetching (API request) were out of sync. So, when this discrepancy was small, our tests didn't catch it. But when we artificially induced a delay in either of those requests, then we saw the same problem of the dropdowns never auto-selecting the correct project.
